# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home
email: lukehinds@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Luke Hinds</h1><h3>Security, clouds, containers and code.</h3>"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gotroot.io" # the base hostname & protocol for your site
twitter_username: lukeahinds
github_username:  lukehinds
google_analytics: "UA-60372167-2"
# Build settings
markdown: kramdown
